version: 2.1
orbs:
  codecov: codecov/codecov@1.0.2
jobs:
  build:
    docker:
      - image: circleci/node:14.10.0-browsers
    working_directory: ~/repo
    parallelism: 4
    steps:
      - checkout
      - restore_cache:
          keys:
            - v2-dependencies-{{ checksum "package.json" }}
      - run: yarn
      - save_cache:
          key: v2-dependencies-{{ checksum "package.json" }}
          paths:
            - node_modules
      - run:
          environment:
            NODE_OPTIONS: --max_old_space_size=4096
          command: yarn install && yarn test:ci
      - codecov/upload:
          file: './coverage/clover.xml'
